global:
  scrape_interval: 1s # Bad!! just for demo. Default is 1 minute.

scrape_configs:
  - job_name: "opentelemetry"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:4000"]
